### PR TITLE
V3.0.0

### PR DESCRIPTION
**Pull request by mrkmg**
Working PR for version 3.0.0

### CODE REVIEW

**Comment by mrkmg** [comment]
This is a major update. Will launch once I can get the docs site up on this repo.

**Comment by hacksparrow** [comment]
Great going, Kevin!

**Comment by mrkmg** [comment]
@hacksparrow I am currently using my fork to host the docs. I would like to host the docs from this repo. Once I launch this, would you be willing to turn on docs to host from the /docs folder?

**Comment by hacksparrow** [comment]
@mrkmg I am not following what you mean by "turn on docs to host from the /docs folder".

**Comment by mrkmg** [comment]
@hacksparrow In the settings for the repo, enable "Github Pages".

image

**Comment by mrkmg** [comment]
You wont be able to do that until I merge this branch into master though. Just want to know if you are willing to enable that.

**Comment by hacksparrow** [comment]
@mrkmg sure, I will do it. Do let me know when I should do it.

**Comment by mrkmg** [comment]
Hey @hacksparrow Can you please setup the Doc's page when you get a chance?

**Comment by mrkmg** [comment]
@hacksparrow Do you have an ETA on the docs page?

**Comment by hacksparrow** [comment]
@mrkmg done - https://hacksparrow.github.io/node-easyimage/

**Pull request merged**
